-- ========================================================
-- Esquema de Base de Datos para Clínica FisioSphere
-- ========================================================
-- Ejecuta este script en el SQL Editor de tu proyecto Supabase.

-- 1. Tabla de Artículos del Blog
CREATE TABLE public.articulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    contenido TEXT,
    autor TEXT NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    categoria TEXT,
    tiempo_lectura TEXT,
    tags TEXT[],
    publicado BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Tabla de Mensajes de Contacto
CREATE TABLE public.contactos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    telefono TEXT,
    mensaje TEXT NOT NULL,
    leido BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Tabla de Citas
CREATE TABLE public.citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT NOT NULL,
    email TEXT NOT NULL,
    servicio TEXT NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    observaciones TEXT,
    estado TEXT DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'confirmada', 'cancelada', 'completada')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================================================
-- Políticas de Seguridad (RLS - Row Level Security)
-- ========================================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.articulos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contactos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.citas ENABLE ROW LEVEL SECURITY;

-- Políticas para Artículos (Blog)
-- Los artículos publicados pueden ser leídos por todos (anónimos y autenticados)
CREATE POLICY "Artículos publicados son públicos" 
ON public.articulos FOR SELECT 
USING (publicado = true);

-- Solo usuarios autenticados (Admin) pueden hacer CRUD en todas las tablas
CREATE POLICY "Admin full access articulos" ON public.articulos FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full access contactos" ON public.contactos FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full access citas" ON public.citas FOR ALL USING (auth.role() = 'authenticated');

-- Políticas para Formularios Públicos (Insertar datos)
-- Cualquier usuario (anónimo) puede insertar en contactos y citas
CREATE POLICY "Cualquiera puede enviar mensajes de contacto" 
ON public.contactos FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Cualquiera puede solicitar citas" 
ON public.citas FOR INSERT 
WITH CHECK (true);

-- ========================================================
-- Triggers (Para actualizar updated_at)
-- ========================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_articulos_modtime
    BEFORE UPDATE ON public.articulos
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
